import type { IconProps } from "@tabler/icons-react"
import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertCircleFilled,
  IconApi,
  IconArrowRight,
  IconArrowsExchange,
  IconAtom2,
  IconBolt,
  IconBook2,
  IconBookmark,
  IconBraces,
  IconBrain,
  IconBulb,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsUp,
  IconClock,
  IconCommand,
  IconCompass,
  IconCopy,
  IconDeviceDesktop,
  IconDeviceLaptop,
  IconDots,
  IconExternalLink,
  IconEye,
  IconFeather,
  IconFileExport,
  IconFileImport,
  IconFileOff,
  IconFileText,
  IconFlag,
  IconGripVertical,
  IconHeart,
  IconHelp,
  IconKeyboard,
  IconLanguage,
  IconLanguageHiragana,
  IconLanguageOff,
  IconLayersIntersect,
  IconLink,
  IconList,
  IconListSearch,
  IconLoader2,
  IconMessage2,
  IconMessageCircle,
  IconMicroscope,
  IconMoon,
  IconNotes,
  IconPalette,
  IconPencil,
  IconPencilCheck,
  IconPlus,
  IconRefresh,
  IconRestore,
  IconSchool,
  IconSearch,
  IconSettings,
  IconSparkles,
  IconSpeakerphone,
  IconStar,
  IconSubtitles,
  IconSun,
  IconTags,
  IconTargetArrow,
  IconTextResize,
  IconTrash,
  IconTypography,
  IconWand,
  IconWorld,
  IconX,
} from "@tabler/icons-react"

const icons = {
  "tabler:star": IconStar,
  "tabler:message-2": IconMessage2,
  "tabler:help": IconHelp,
  "tabler:chevron-down": IconChevronDown,
  "tabler:eye": IconEye,
  "tabler:pencil": IconPencil,
  "tabler:plus": IconPlus,
  "tabler:copy": IconCopy,
  "tabler:trash": IconTrash,
  "tabler:check": IconCheck,
  "tabler:file-import": IconFileImport,
  "tabler:x": IconX,
  "tabler:chevron-left": IconChevronLeft,
  "tabler:chevron-right": IconChevronRight,
  "tabler:sparkles": IconSparkles,
  "tabler:subtitles": IconSubtitles,
  "tabler:keyboard": IconKeyboard,
  "tabler:layers-intersect": IconLayersIntersect,
  "tabler:speakerphone": IconSpeakerphone,
  "tabler:language-hiragana": IconLanguageHiragana,
  "tabler:api": IconApi,
  "tabler:adjustments-horizontal": IconAdjustmentsHorizontal,
  "tabler:command": IconCommand,
  "tabler:chevron-up": IconChevronUp,
  "tabler:braces": IconBraces,
  "tabler:list-search": IconListSearch,
  "tabler:alert-circle": IconAlertCircle,
  "tabler:list": IconList,
  "tabler:book-2": IconBook2,
  "tabler:bookmark": IconBookmark,
  "tabler:search": IconSearch,
  "tabler:settings": IconSettings,
  "tabler:bulb": IconBulb,
  "tabler:brain": IconBrain,
  "tabler:heart": IconHeart,
  "tabler:message-circle": IconMessageCircle,
  "tabler:notes": IconNotes,
  "tabler:file-text": IconFileText,
  "tabler:flag": IconFlag,
  "tabler:clock": IconClock,
  "tabler:calendar": IconCalendar,
  "tabler:bolt": IconBolt,
  "tabler:compass": IconCompass,
  "tabler:palette": IconPalette,
  "tabler:feather": IconFeather,
  "tabler:device-laptop": IconDeviceLaptop,
  "tabler:school": IconSchool,
  "tabler:microscope": IconMicroscope,
  "tabler:atom-2": IconAtom2,
  "tabler:target-arrow": IconTargetArrow,
  "tabler:world": IconWorld,
  "tabler:link": IconLink,
  "tabler:tags": IconTags,
  "tabler:wand": IconWand,
  "tabler:dots": IconDots,
  "tabler:external-link": IconExternalLink,
  "tabler:grip-vertical": IconGripVertical,
  "tabler:arrows-exchange": IconArrowsExchange,
  "tabler:arrow-right": IconArrowRight,
  "tabler:device-desktop": IconDeviceDesktop,
  "tabler:sun": IconSun,
  "tabler:moon": IconMoon,
  "tabler:restore": IconRestore,
  "tabler:file-export": IconFileExport,
  "tabler:file-off": IconFileOff,
  "tabler:alert-circle-filled": IconAlertCircleFilled,
  "tabler:refresh": IconRefresh,
  "tabler:typography": IconTypography,
  "tabler:language": IconLanguage,
  "tabler:text-resize": IconTextResize,
  "tabler:loader-2": IconLoader2,
  "tabler:chevrons-down": IconChevronsDown,
  "tabler:chevrons-up": IconChevronsUp,
  "tabler:language-off": IconLanguageOff,
  "tabler:pencil-check": IconPencilCheck,
  "ri:translate": IconLanguage,
  "garden:translation-exists-stroke-16": IconLanguage,
}

export function Icon({ icon, ...props }: IconProps & { icon: string }) {
  const Component = icons[icon as keyof typeof icons] ?? IconSparkles
  return <Component {...props} />
}
